<a href="https://colab.research.google.com/github/SrivalliMbg/Srivalli.M/blob/main/BLA0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Inner product**

an inner product is a generalized dot product that combines two vectors to produce a single number.The inner product is also known as the dot product or scalar product.


i.e., if a,b are column matrices with same dimention,

### the inner poduct of a,b= (a^T).b

## **Outer product**

 the outer product of two vectors is a matrix where each entry is the product of an element from the first vector and an element from the second vector.

i.e.,
### the outer porduct of a,b= a.(b^T)





In [ ]:
import numpy as np

In [ ]:
#to calculate inner product of a,b
a = np.array([3,7,5])
b = np.array([6,3,9])
inner_product = np.inner(a,b)
print(inner_product)

18


In [ ]:
#to calculate outer broduct of a,b
 a = np.array([6,8,4])
 b = np.array([9,3,7])
 outer_product = np.outer(a,b)
 print(outer_product)

[[54 18 42]
 [72 24 56]
 [36 12 28]]


## **Norm of matrix**

The norm of a matrix is a real number which is a measure of the magnitude of the matrix.Norm of a matrix is defined as square root of sum of squares of matrix elements.

### Norm of matrix= sqrt(trace of matrix)

In [ ]:
 a = ([6,8,4],[4,6,2],[8,4,2])
 norm=np.linalg.norm(a)
 print(norm)

16.0
